# Generated by Django 4.0.4 on 2022-06-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_answer_profile_question_test_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.IntegerField(unique=True),
        ),
    ]
