# Generated by Django 4.0.4 on 2022-06-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_answer_question_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pregunta',
            field=models.CharField(max_length=255),
        ),
    ]
