# Generated by Django 4.0.4 on 2022-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_profile_dni_alter_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
