# Generated by Django 4.0.4 on 2022-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_profile_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
